import {
  Camera,
  SecurityAlert,
  EventLogItem,
  ANPRRecord,
  FaceDetectionRecord,
  VirtualFenceZone,
  AIModelSpec,
  SystemHealthMetrics,
} from './types';

export const INITIAL_CAMERAS: Camera[] = [
  {
    id: 'BOP-01',
    name: 'Forward Outpost Alpha',
    location: 'Ridge Line Sector 4-A',
    status: 'ONLINE',
    type: 'OPTICAL',
    rtspUrl: 'rtsp://10.24.101.12:554/live/stream1',
    fps: 30,
    resolution: '3840x2160 (4K)',
    detectedCount: 2,
    aiConfidence: 0.94,
    aiEnabled: true,
    lastSeen: 'Just now',
    coordinates: { lat: 32.4182, lng: 74.8812, mapX: 24, mapY: 32 },
    activeAlerts: 0,
    irMode: false,
  },
  {
    id: 'BOP-02',
    name: 'Riverine Sector Beta',
    location: 'Ravi River Basin Segment 2',
    status: 'ALERT',
    type: 'THERMAL_IR',
    rtspUrl: 'rtsp://10.24.101.14:554/thermal/ch1',
    fps: 25,
    resolution: '1920x1080 (FHD)',
    detectedCount: 3,
    aiConfidence: 0.96,
    aiEnabled: true,
    lastSeen: 'Just now',
    coordinates: { lat: 32.435, lng: 74.9125, mapX: 42, mapY: 48 },
    activeAlerts: 1,
    irMode: true,
  },
  {
    id: 'BORDER-ROAD-03',
    name: 'Transit Corridor Delta',
    location: 'Patrol Track KM 14.8',
    status: 'ONLINE',
    type: 'NIGHT_VISION',
    rtspUrl: 'rtsp://10.24.102.05:554/nv/h265',
    fps: 30,
    resolution: '2560x1440 (2K)',
    detectedCount: 1,
    aiConfidence: 0.91,
    aiEnabled: true,
    lastSeen: 'Just now',
    coordinates: { lat: 32.451, lng: 74.935, mapX: 61, mapY: 28 },
    activeAlerts: 0,
    irMode: false,
  },
  {
    id: 'CHECKPOST-04',
    name: 'Checkpost Echo Gate',
    location: 'Entry Checkpoint Gate 02',
    status: 'ONLINE',
    type: 'ANPR_HIGHRES',
    rtspUrl: 'rtsp://10.24.103.22:554/anpr/feed',
    fps: 30,
    resolution: '3840x2160 (4K)',
    detectedCount: 2,
    aiConfidence: 0.93,
    aiEnabled: true,
    lastSeen: 'Just now',
    coordinates: { lat: 32.428, lng: 74.962, mapX: 78, mapY: 65 },
    activeAlerts: 0,
    irMode: false,
  },
  {
    id: 'WATCHTOWER-05',
    name: 'Elevated Sector Foxtrot',
    location: 'Hilltop Observation Post 09',
    status: 'WARNING',
    type: 'RADAR_PTZ',
    rtspUrl: 'rtsp://10.24.104.08:554/ptz/main',
    fps: 24,
    resolution: '1920x1080 (FHD)',
    detectedCount: 1,
    aiConfidence: 0.88,
    aiEnabled: true,
    lastSeen: '3s ago',
    coordinates: { lat: 32.468, lng: 74.895, mapX: 35, mapY: 18 },
    activeAlerts: 1,
    irMode: false,
  },
  {
    id: 'PERIMETER-06',
    name: 'Perimeter Smart Fence',
    location: 'Sector Gamma Sensor Line',
    status: 'ONLINE',
    type: 'THERMAL_IR',
    rtspUrl: 'rtsp://10.24.105.18:554/thermal/ir2',
    fps: 30,
    resolution: '1920x1080 (FHD)',
    detectedCount: 0,
    aiConfidence: 0.95,
    aiEnabled: true,
    lastSeen: 'Just now',
    coordinates: { lat: 32.405, lng: 74.945, mapX: 85, mapY: 40 },
    activeAlerts: 0,
    irMode: true,
  },
];

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'ALT-9041',
    title: 'Virtual Fence Breach Detected',
    cameraId: 'BOP-02',
    cameraName: 'Riverine Sector Beta',
    location: 'Ravi River Basin Segment 2',
    timestamp: '20:12:45 IST',
    severity: 'CRITICAL',
    status: 'NEW',
    category: 'VIRTUAL_FENCE_BREACH',
    objectType: 'PERSON (x2)',
    confidence: 0.96,
    description: 'Two human heat signatures crossed dynamic virtual tripwire #3 into restricted buffer zone.',
    recommendedAction: 'Dispatch Quick Reaction Team (QRT) Unit Bravo and illuminate sector floodlights.',
    movementVector: 'North-East 2.4 m/s',
    zone: 'Sector Beta Buffer',
  },
  {
    id: 'ALT-9038',
    title: 'Suspicious Night-Time Movement',
    cameraId: 'WATCHTOWER-05',
    cameraName: 'Elevated Sector Foxtrot',
    location: 'Hilltop Observation Post 09',
    timestamp: '20:06:12 IST',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    category: 'NIGHT_MOVEMENT',
    objectType: 'PERSON',
    confidence: 0.88,
    description: 'Low-light thermal movement detected in blind foliage valley outside designated patrol corridor.',
    recommendedAction: 'Re-align PTZ focal zoom and verify with thermal drone patrol.',
    movementVector: 'South-West 1.1 m/s',
    zone: 'Foliage Ridge 09',
  },
  {
    id: 'ALT-9032',
    title: 'Unregistered Heavy Vehicle at Checkpost',
    cameraId: 'CHECKPOST-04',
    cameraName: 'Checkpost Echo Gate',
    location: 'Entry Checkpoint Gate 02',
    timestamp: '19:48:30 IST',
    severity: 'MEDIUM',
    status: 'ACKNOWLEDGED',
    category: 'UNKNOWN_VEHICLE',
    objectType: 'TRUCK',
    confidence: 0.92,
    description: 'Commercial flatbed truck lacking active RFID border transit authorization barcode.',
    recommendedAction: 'Divert vehicle to secondary inspection bay and execute manual credential verification.',
    zone: 'Gate 02 Approach',
  },
  {
    id: 'ALT-9025',
    title: 'Prolonged Loitering Near Perimeter',
    cameraId: 'BORDER-ROAD-03',
    cameraName: 'Transit Corridor Delta',
    location: 'Patrol Track KM 14.8',
    timestamp: '19:15:00 IST',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    category: 'SUSPICIOUS_LOITERING',
    objectType: 'PERSON',
    confidence: 0.89,
    description: 'Subject lingered adjacent to outer culvert fence for > 6 minutes before heading east.',
    recommendedAction: 'Foot patrol verified local farmer tending stray cattle; perimeter secure.',
    zone: 'Culvert 14.8',
  },
];

export const INITIAL_EVENTS: EventLogItem[] = [
  {
    id: 'EVT-8891',
    timestamp: '20:12:45 IST',
    cameraId: 'BOP-02',
    location: 'Ravi River Basin Segment 2',
    eventType: 'Virtual Fence Breach',
    object: 'PERSON',
    confidence: 0.96,
    severity: 'CRITICAL',
    status: 'FLAGGED',
    details: 'Tripwire cross detected by Thermal IR model v3.4 at boundary line.',
  },
  {
    id: 'EVT-8890',
    timestamp: '20:10:14 IST',
    cameraId: 'CHECKPOST-04',
    location: 'Entry Checkpoint Gate 02',
    eventType: 'ANPR Vehicle Verification',
    object: 'SUV',
    confidence: 0.95,
    severity: 'LOW',
    status: 'PROCESSED',
    details: 'License plate DL 04 AB 8841 verified with Border Gate manifest.',
  },
  {
    id: 'EVT-8889',
    timestamp: '20:06:12 IST',
    cameraId: 'WATCHTOWER-05',
    location: 'Hilltop Observation Post 09',
    eventType: 'Night Foliage Movement',
    object: 'PERSON',
    confidence: 0.88,
    severity: 'HIGH',
    status: 'FLAGGED',
    details: 'Thermal delta detected: 37.1 C object moving through 18 C foliage.',
  },
  {
    id: 'EVT-8888',
    timestamp: '19:58:33 IST',
    cameraId: 'BOP-01',
    location: 'Ridge Line Sector 4-A',
    eventType: 'Patrol Vehicle In-transit',
    object: 'VEHICLE',
    confidence: 0.94,
    severity: 'LOW',
    status: 'PROCESSED',
    details: 'BSF Reconnaissance Jeep Unit 14 registered passing checkpoint.',
  },
  {
    id: 'EVT-8887',
    timestamp: '19:48:30 IST',
    cameraId: 'CHECKPOST-04',
    location: 'Entry Checkpoint Gate 02',
    eventType: 'Unknown Vehicle Flagged',
    object: 'TRUCK',
    confidence: 0.92,
    severity: 'MEDIUM',
    status: 'FLAGGED',
    details: 'Heavy commercial truck plate PB 10 Z 9901 flagged for manual clearance.',
  },
  {
    id: 'EVT-8886',
    timestamp: '19:35:10 IST',
    cameraId: 'PERIMETER-06',
    location: 'Sector Gamma Sensor Line',
    eventType: 'Wildlife Proximity Sensor',
    object: 'ANIMAL',
    confidence: 0.91,
    severity: 'LOW',
    status: 'RESOLVED',
    details: 'Canine/Wolf classified near fence buffer; no human intrusion detected.',
  },
];

export const INITIAL_ANPR: ANPRRecord[] = [
  {
    id: 'ANPR-101',
    timestamp: '20:10:14 IST',
    camera: 'CHECKPOST-04',
    location: 'Entry Checkpoint Gate 02',
    vehicleType: 'SUV',
    plateNumber: 'DL 04 AB 8841',
    confidence: 0.95,
    status: 'VERIFIED',
    speedKmh: 24,
    direction: 'INBOUND',
    isSimulated: true,
  },
  {
    id: 'ANPR-102',
    timestamp: '19:48:30 IST',
    camera: 'CHECKPOST-04',
    location: 'Entry Checkpoint Gate 02',
    vehicleType: 'TRUCK',
    plateNumber: 'PB 10 Z 9901',
    confidence: 0.92,
    status: 'UNKNOWN',
    speedKmh: 18,
    direction: 'INBOUND',
    isSimulated: true,
  },
  {
    id: 'ANPR-103',
    timestamp: '19:22:15 IST',
    camera: 'BORDER-ROAD-03',
    location: 'Patrol Track KM 14.8',
    vehicleType: 'SEDAN',
    plateNumber: 'HR 26 CY 4419',
    confidence: 0.94,
    status: 'VERIFIED',
    speedKmh: 42,
    direction: 'OUTBOUND',
    isSimulated: true,
  },
  {
    id: 'ANPR-104',
    timestamp: '18:55:02 IST',
    camera: 'CHECKPOST-04',
    location: 'Entry Checkpoint Gate 02',
    vehicleType: 'MOTORCYCLE',
    plateNumber: 'JK 02 BB 1209',
    confidence: 0.89,
    status: 'VERIFIED',
    speedKmh: 35,
    direction: 'INBOUND',
    isSimulated: true,
  },
  {
    id: 'ANPR-105',
    timestamp: '18:10:44 IST',
    camera: 'CHECKPOST-04',
    location: 'Entry Checkpoint Gate 02',
    vehicleType: 'TRUCK',
    plateNumber: 'MH 12 QX 5580',
    confidence: 0.96,
    status: 'FLAGGED',
    speedKmh: 12,
    direction: 'INBOUND',
    isSimulated: true,
  },
];

export const INITIAL_FACES: FaceDetectionRecord[] = [
  {
    id: 'FACE-501',
    timestamp: '20:12:45 IST',
    camera: 'BOP-02',
    location: 'Ravi River Basin Segment 2',
    faceId: 'F-SIM-99214',
    confidence: 0.89,
    matchScore: 0.92,
    status: 'WATCHLIST_MATCH',
    matchedIdentity: {
      name: 'Simulated Subject #41',
      alias: 'Vector Shadow',
      threatClass: 'Class B Infiltrator (Demo Identity)',
      fictionalNotice: 'DEMO PROTOTYPE ONLY - Fictional simulation record for hackathon evaluation.',
    },
    features: {
      embeddings: '512D Vector Hash: e8a1...9b2c',
      pitch: -4.2,
      yaw: 12.8,
      lighting: 'Thermal Low-Lux (0.02 Lux)',
    },
  },
  {
    id: 'FACE-502',
    timestamp: '19:58:33 IST',
    camera: 'BOP-01',
    location: 'Ridge Line Sector 4-A',
    faceId: 'F-AUTH-1002',
    confidence: 0.97,
    matchScore: 0.98,
    status: 'AUTHORIZED_PERSONNEL',
    matchedIdentity: {
      name: 'Officer Vikram Singh',
      alias: 'Command Lead',
      threatClass: 'Authorized BSF Officer',
      fictionalNotice: 'Simulated authorized personnel record.',
    },
    features: {
      embeddings: '512D Vector Hash: a112...07ff',
      pitch: 1.1,
      yaw: -2.3,
      lighting: 'Full Daylight Optical',
    },
  },
  {
    id: 'FACE-503',
    timestamp: '19:15:00 IST',
    camera: 'BORDER-ROAD-03',
    location: 'Patrol Track KM 14.8',
    faceId: 'F-UNK-3401',
    confidence: 0.87,
    matchScore: 0.31,
    status: 'UNKNOWN_DETECTED',
    features: {
      embeddings: '512D Vector Hash: 44cf...881a',
      pitch: 8.5,
      yaw: -15.4,
      lighting: 'Infrared Night Vision',
    },
  },
];

export const INITIAL_ZONES: VirtualFenceZone[] = [
  {
    id: 'ZONE-ALPHA',
    name: 'Sector Alpha Zero Line',
    polygon: [
      { x: 15, y: 20 },
      { x: 38, y: 25 },
      { x: 35, y: 38 },
      { x: 12, y: 32 },
    ],
    status: 'ARMED',
    color: '#00f0ff',
    sector: 'Ridge Outpost Line',
    severity: 'CRITICAL',
  },
  {
    id: 'ZONE-BETA',
    name: 'Sector Beta River Corridor',
    polygon: [
      { x: 36, y: 40 },
      { x: 58, y: 44 },
      { x: 55, y: 58 },
      { x: 34, y: 54 },
    ],
    status: 'BREACHED',
    color: '#ef4444',
    sector: 'Ravi River Marshes',
    severity: 'CRITICAL',
  },
  {
    id: 'ZONE-GAMMA',
    name: 'Sector Gamma Electric Fence Line',
    polygon: [
      { x: 62, y: 25 },
      { x: 88, y: 32 },
      { x: 86, y: 48 },
      { x: 60, y: 42 },
    ],
    status: 'ARMED',
    color: '#10b981',
    sector: 'Eastern Buffer Highway',
    severity: 'HIGH',
  },
];

export const INITIAL_MODELS: AIModelSpec[] = [
  {
    id: 'MOD-01',
    name: 'YOLOv10x Person Detector',
    category: 'Human Detection & Multi-Object Tracking',
    status: 'ACTIVE',
    accuracy: 94.6,
    inferenceFps: 32,
    latencyMs: 14.2,
    version: 'v10.3.1-trt-fp16',
    gpuMemoryMb: 2450,
    confidenceThreshold: 70,
    description: 'TensorRT-optimized deep neural network for pedestrian, border crosser, and posture classification.',
  },
  {
    id: 'MOD-02',
    name: 'Vehicle & Convoy Classifier',
    category: 'Vehicle Analytics & Classification',
    status: 'ACTIVE',
    accuracy: 96.2,
    inferenceFps: 38,
    latencyMs: 11.5,
    version: 'v4.1.0-trt',
    gpuMemoryMb: 1820,
    confidenceThreshold: 65,
    description: 'Distinguishes military convoys, commercial trucks, SUVs, civilian vehicles, and motorcycles.',
  },
  {
    id: 'MOD-03',
    name: 'Thermal IR Night Movement Detector',
    category: 'Night Surveillance & Low-Lux Vision',
    status: 'ACTIVE',
    accuracy: 93.8,
    inferenceFps: 28,
    latencyMs: 16.8,
    version: 'v2.8-flir-opt',
    gpuMemoryMb: 2100,
    confidenceThreshold: 75,
    description: 'Extracts differential body heat signatures through fog, dense foliage, and total darkness.',
  },
  {
    id: 'MOD-04',
    name: 'DeepPlate ANPR Engine',
    category: 'Automatic Number Plate Recognition',
    status: 'ACTIVE',
    accuracy: 95.1,
    inferenceFps: 42,
    latencyMs: 9.8,
    version: 'v5.2-ocr-multi',
    gpuMemoryMb: 1640,
    confidenceThreshold: 80,
    description: 'Sub-millisecond character segmentation and national registry cross-reference matching.',
  },
  {
    id: 'MOD-05',
    name: 'ArcFace Border Watchlist Matcher',
    category: 'Facial Biometrics & Verification',
    status: 'ACTIVE',
    accuracy: 92.4,
    inferenceFps: 24,
    latencyMs: 19.5,
    version: 'v3.6-512d',
    gpuMemoryMb: 3100,
    confidenceThreshold: 85,
    description: 'Generates 512-dimensional facial embedding vectors with cosine distance matching.',
  },
  {
    id: 'MOD-06',
    name: 'Virtual Perimeter Geofence Engine',
    category: 'Intrusion Detection & Tripwire Logic',
    status: 'ACTIVE',
    accuracy: 98.5,
    inferenceFps: 60,
    latencyMs: 4.1,
    version: 'v6.0-vector-logic',
    gpuMemoryMb: 520,
    confidenceThreshold: 75,
    description: 'Spatial vector intersection calculating trajectory, velocity, and boundary intrusion angles.',
  },
  {
    id: 'MOD-07',
    name: 'Behavior & Loitering Analytics',
    category: 'Spatiotemporal Pattern Analysis',
    status: 'ACTIVE',
    accuracy: 91.2,
    inferenceFps: 26,
    latencyMs: 18.2,
    version: 'v2.1-lstm-graph',
    gpuMemoryMb: 2200,
    confidenceThreshold: 70,
    description: 'Identifies abnormal lingering, sudden running, perimeter pacing, and crowd formation.',
  },
  {
    id: 'MOD-08',
    name: 'DeepSORT Multi-Target Tracker',
    category: 'Persistent Object Association',
    status: 'ACTIVE',
    accuracy: 94.0,
    inferenceFps: 35,
    latencyMs: 12.0,
    version: 'v3.2-kalman-reid',
    gpuMemoryMb: 1450,
    confidenceThreshold: 60,
    description: 'Maintains consistent track IDs through occlusions, camera handoffs, and terrain obstacles.',
  },
];

export const INITIAL_HEALTH: SystemHealthMetrics = {
  cpuUsage: 34.2,
  gpuUsage: 68.5,
  ramUsageGb: 22.4,
  ramTotalGb: 64.0,
  gpuVramGb: 14.8,
  gpuTotalVramGb: 48.0,
  networkInMbps: 184.2,
  networkOutMbps: 92.6,
  storageUsedGb: 4820,
  storageTotalGb: 16000,
  activeStreams: 6,
  cameraHealthPct: 98.4,
  aiProcessingFps: 28.6,
  apiLatencyMs: 12,
  uptimeSeconds: 84620,
};
